#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2013 Dag Wieers (dag@wieers.com)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

export DESTDIR=$PWD/$INSTALL
cd $PKG_BUILD

make install

cd $ROOT

rm -f $INSTALL/usr/lib/libtorrent-rasterbar.a
rm -f $INSTALL/usr/lib/libtorrent-rasterbar.la
rm -f $INSTALL/usr/lib/pkgconfig/libtorrent-rasterbar.pc
rm -fr $INSTALL/usr/include/libtorrent
